spring.application.name=bai_tap_song

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/thong_tin_bai_hat?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
